[project]
name = 'Decentralized-Crop-Insurance-for-Climate-Resilience'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.climate-data-oracle]
path = 'contracts/climate-data-oracle.clar'
clarity_version = 2
epoch = 2.5

[contracts.farm-registration]
path = 'contracts/farm-registration.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
